In [1]:
import os
import numpy as np
import cv2
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
data_path = os.path.join("../Data")
test_data_path = os.path.join(data_path, "asl_alphabet_test/asl_alphabet_test")

In [3]:
IMG_SIZE = (128, 128)
BATCH_SIZE = 64

In [4]:
# Load the trained model
model = load_model("./asl_model.h5")

# Classes
classes = [
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K',
    'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V',
    'W', 'X', 'Y', 'Z'
]

In [5]:
datagen = ImageDataGenerator(rescale=1.0 / 255)

test_generator = datagen.flow_from_directory(
    test_data_path,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

Found 26 images belonging to 26 classes.


In [6]:
test_loss, test_acc = model.evaluate(test_generator, verbose=1)
print(f"Test Accuracy: {test_acc:.2f}, Test Loss: {test_loss:.2f}")

c:\Users\Shruti\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\trainers\data_adapters\py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 1.0000 - loss: 0.0014
Test Accuracy: 1.00, Test Loss: 0.00


In [7]:
predictions = model.predict(test_generator, verbose=1)
y_pred = np.argmax(predictions, axis=1)
y_true = test_generator.classes

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step


In [10]:
print("\nPredicted Labels:\n")
for i, pred in enumerate(predictions):
    predicted_class_index = np.argmax(pred)
    predicted_label = classes[predicted_class_index]
    true_label_index = test_generator.classes[i]
    true_label = classes[true_label_index]
    print(f"Image {i + 1}: Predicted - {predicted_label}, True - {true_label}")


Predicted Labels:

Image 1: Predicted - A, True - A
Image 2: Predicted - B, True - B
Image 3: Predicted - C, True - C
Image 4: Predicted - D, True - D
Image 5: Predicted - E, True - E
Image 6: Predicted - F, True - F
Image 7: Predicted - G, True - G
Image 8: Predicted - H, True - H
Image 9: Predicted - I, True - I
Image 10: Predicted - J, True - J
Image 11: Predicted - K, True - K
Image 12: Predicted - L, True - L
Image 13: Predicted - M, True - M
Image 14: Predicted - N, True - N
Image 15: Predicted - O, True - O
Image 16: Predicted - P, True - P
Image 17: Predicted - Q, True - Q
Image 18: Predicted - R, True - R
Image 19: Predicted - S, True - S
Image 20: Predicted - T, True - T
Image 21: Predicted - U, True - U
Image 22: Predicted - V, True - V
Image 23: Predicted - W, True - W
Image 24: Predicted - X, True - X
Image 25: Predicted - Y, True - Y
Image 26: Predicted - Z, True - Z


In [8]:
print("\nClassification Report:\n")
print(classification_report(y_true, y_pred, target_names=classes))


Classification Report:

              precision    recall  f1-score   support

           A       1.00      1.00      1.00         1
           B       1.00      1.00      1.00         1
           C       1.00      1.00      1.00         1
           D       1.00      1.00      1.00         1
           E       1.00      1.00      1.00         1
           F       1.00      1.00      1.00         1
           G       1.00      1.00      1.00         1
           H       1.00      1.00      1.00         1
           I       1.00      1.00      1.00         1
           J       1.00      1.00      1.00         1
           K       1.00      1.00      1.00         1
           L       1.00      1.00      1.00         1
           M       1.00      1.00      1.00         1
           N       1.00      1.00      1.00         1
           O       1.00      1.00      1.00         1
           P       1.00      1.00      1.00         1
           Q       1.00      1.00      1.00         1
  

In [9]:
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_true, y_pred))


Confusion Matrix:

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0